In [134]:
# pip install googletrans==4.0.0rc1

In [133]:
# pip install clean-text

In [ ]:
# bow = "penghantaran, poslaju, cepat, lambat, perlahan lahan, tepat pada masanya, hantar"
# delivery/shipping, postage, fast/quick , slow, slowly, on time, shipping, send

In [1]:
import string
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup 
import re # For regular expressions
from cleantext import clean


from googletrans import Translator

In [56]:
df = pd.read_csv('/Users/shureenteh/Downloads/smu stuff/year 3 sem 2/is434/project data/data/tissue.csv')

In [57]:
df

,username,date,variation,rating,comment
0,r*****.,2022-03-05 19:20:02,NaN,5,Daya serap:belum d coba\nKetebalan:belum d cob...
1,cheppylesmana,2022-03-05 18:44:34,NaN,5,Ketebalan:Sesuai👍👍👍\nKelembutan:Banget👍👍👍\nDay...
2,lenayosep16,2022-03-05 18:20:55,NaN,5,Sangat rekomendasi untuk di beli dan saya juga...
3,nadi379,2022-03-06 12:57:36,NaN,5,Sudah diterima produknya. Selalu puas dengan p...
4,nouroh,2022-02-26 13:30:34,NaN,5,Alhmdulillah sampe nya cepet produknya baik pe...
...,...,...,...,...,...
3015,y*****0,2022-01-19 10:01:32,NaN,5,Daya serap:mantap& selalu langganan\n\nHalus t...
3016,y*****0,2022-01-19 10:08:15,NaN,5,Daya serap:mantap lembut dan menyerap makanya ...
3017,thalia.permata.sari,2022-01-20 17:36:53,NaN,4,Ketebalan:ok\nKelembutan:ok\nDaya serap:ok\n\n...
3018,r*****8,2022-01-15 18:11:30,NaN,5,Ketebalan:lumayan\nKelembutan:lumayan\nDaya se...
3019,alfirevan,2022-01-14 14:41:42,NaN,3,Ketebalan:ok\nKelembutan:bagus\nDaya serap:ok\...

In [58]:
def clean_text_round1(text):
    '''Make text lowercase, remove punctuation, remove words containing numbers and lemmatize/stem.'''
    text = str(text).lower()
    text = re.sub('#\w*', '', text)
    text = re.sub('@\w*', '', text)    
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\w*\d\w*', '', text)
    text = clean(text, no_emoji=True)
    return text

# Let's take a look at the updated text
df['clean'] = pd.DataFrame(df['comment'].apply(clean_text_round1))
df

,username,date,variation,rating,comment,clean
0,r*****.,2022-03-05 19:20:02,NaN,5,Daya serap:belum d coba\nKetebalan:belum d cob...,daya serapbelum d coba\nketebalanbelum d coba\...
1,cheppylesmana,2022-03-05 18:44:34,NaN,5,Ketebalan:Sesuai👍👍👍\nKelembutan:Banget👍👍👍\nDay...,ketebalansesuai\nkelembutanbanget\ndaya serapb...
2,lenayosep16,2022-03-05 18:20:55,NaN,5,Sangat rekomendasi untuk di beli dan saya juga...,sangat rekomendasi untuk di beli dan saya juga...
3,nadi379,2022-03-06 12:57:36,NaN,5,Sudah diterima produknya. Selalu puas dengan p...,sudah diterima produknya selalu puas dengan te...
4,nouroh,2022-02-26 13:30:34,NaN,5,Alhmdulillah sampe nya cepet produknya baik pe...,alhmdulillah sampe nya cepet produknya baik pe...
...,...,...,...,...,...,...
3015,y*****0,2022-01-19 10:01:32,NaN,5,Daya serap:mantap& selalu langganan\n\nHalus t...,daya serapmantap selalu langganan\nhalus tisun...
3016,y*****0,2022-01-19 10:08:15,NaN,5,Daya serap:mantap lembut dan menyerap makanya ...,daya serapmantap lembut dan menyerap makanya s...
3017,thalia.permata.sari,2022-01-20 17:36:53,NaN,4,Ketebalan:ok\nKelembutan:ok\nDaya serap:ok\n\n...,ketebalanok\nkelembutanok\ndaya serapok\nterim...
3018,r*****8,2022-01-15 18:11:30,NaN,5,Ketebalan:lumayan\nKelembutan:lumayan\nDaya se...,ketebalanlumayan\nkelembutanlumayan\ndaya sera...
3019,alfirevan,2022-01-14 14:41:42,NaN,3,Ketebalan:ok\nKelembutan:bagus\nDaya serap:ok\...,ketebalanok\nkelembutanbagus\ndaya serapok\nma...

In [59]:
df['clean'] = df['clean'].str.replace('\n',' ')

In [60]:
df['clean']

0       daya serapbelum d coba ketebalanbelum d coba k...
1       ketebalansesuai kelembutanbanget daya serapbai...
2       sangat rekomendasi untuk di beli dan saya juga...
3       sudah diterima produknya selalu puas dengan te...
4       alhmdulillah sampe nya cepet produknya baik pe...
                              ...
3015    daya serapmantap selalu langganan halus tisuny...
3016    daya serapmantap lembut dan menyerap makanya s...
3017    ketebalanok kelembutanok daya serapok terima k...
3018    ketebalanlumayan kelembutanlumayan daya serapl...
3019    ketebalanok kelembutanbagus daya serapok maaf ...
Name: clean, Length: 3020, dtype: object

In [61]:
df1 = df[df['clean'].str.contains("pengiriman")]

In [62]:
df1

,username,date,variation,rating,comment,clean
4,nouroh,2022-02-26 13:30:34,NaN,5,Alhmdulillah sampe nya cepet produknya baik pe...,alhmdulillah sampe nya cepet produknya baik pe...
5,mariabeautyseries,2022-02-28 22:57:39,NaN,4,Ketebalan:baik\nKelembutan:baik\nDaya serap:ba...,ketebalanbaik kelembutanbaik daya serapbaik pe...
6,brosist_olshop,2022-03-06 13:31:34,NaN,4,Ketebalan:ok\nKelembutan:lembut\nDaya serap:ba...,ketebalanok kelembutanlembut daya serapbagus p...
8,almirariana,2022-03-07 13:40:25,NaN,4,Ketebalan:lumayan\nKelembutan:ok\nDaya serap:o...,ketebalanlumayan kelembutanok daya serapok pen...
9,m*****1,2022-03-06 22:57:06,NaN,5,Kelembutan:lembut\nDaya serap:menyerap\nKeteba...,kelembutanlembut daya serapmenyerap ketebalant...
...,...,...,...,...,...,...
3007,g*****h,2022-01-11 17:38:11,NaN,5,Mantap. Pengiriman cepat. Kmrin pesan tadi pag...,mantap pengiriman cepat kmrin pesan tadi pagi ...
3008,m*****i,2022-01-14 20:52:42,NaN,5,Pengiriman cepat pengemasan okeh aman tisu nya...,pengiriman cepat pengemasan okeh aman tisu nya...
3014,marlinhyekyo,2022-01-13 19:28:39,NaN,5,"Harga murah, pengiriman cepat, packing aman......",harga murah pengiriman cepat packing aman mant...
3017,thalia.permata.sari,2022-01-20 17:36:53,NaN,4,Ketebalan:ok\nKelembutan:ok\nDaya serap:ok\n\n...,ketebalanok kelembutanok daya serapok terima k...
3018,r*****8,2022-01-15 18:11:30,NaN,5,Ketebalan:lumayan\nKelembutan:lumayan\nDaya se...,ketebalanlumayan kelembutanlumayan daya serapl...

In [63]:
df2 = df1[df1['clean'].str.contains("cepat")]

In [64]:
df2
#288 rows

,username,date,variation,rating,comment,clean
5,mariabeautyseries,2022-02-28 22:57:39,NaN,4,Ketebalan:baik\nKelembutan:baik\nDaya serap:ba...,ketebalanbaik kelembutanbaik daya serapbaik pe...
6,brosist_olshop,2022-03-06 13:31:34,NaN,4,Ketebalan:ok\nKelembutan:lembut\nDaya serap:ba...,ketebalanok kelembutanlembut daya serapbagus p...
8,almirariana,2022-03-07 13:40:25,NaN,4,Ketebalan:lumayan\nKelembutan:ok\nDaya serap:o...,ketebalanlumayan kelembutanok daya serapok pen...
9,m*****1,2022-03-06 22:57:06,NaN,5,Kelembutan:lembut\nDaya serap:menyerap\nKeteba...,kelembutanlembut daya serapmenyerap ketebalant...
10,devidianitta,2022-03-06 12:21:23,NaN,5,Daya serap:keren\nKetebalan:bagus\nKelembutan:...,daya serapkeren ketebalanbagus kelembutanorigi...
...,...,...,...,...,...,...
3005,m*****i,2022-01-14 20:54:13,NaN,5,Pengiriman cepat pengemasan packingan okeh ama...,pengiriman cepat pengemasan packingan okeh ama...
3006,henylilis,2022-01-14 17:46:56,NaN,5,Pengiriman cepat harga murah...entah udah brp ...,pengiriman cepat harga murahentah udah brp kal...
3007,g*****h,2022-01-11 17:38:11,NaN,5,Mantap. Pengiriman cepat. Kmrin pesan tadi pag...,mantap pengiriman cepat kmrin pesan tadi pagi ...
3008,m*****i,2022-01-14 20:52:42,NaN,5,Pengiriman cepat pengemasan okeh aman tisu nya...,pengiriman cepat pengemasan okeh aman tisu nya...
3014,marlinhyekyo,2022-01-13 19:28:39,NaN,5,"Harga murah, pengiriman cepat, packing aman......",harga murah pengiriman cepat packing aman mant...

In [65]:
df3 = df1[df1['clean'].str.contains("lambat")]

In [67]:
df3

Empty DataFrame
Columns: [username, date, variation, rating, comment, clean]
Index: []

In [24]:
# df.loc[df['clean'].map(lambda x: [x for x in l if l in ['penghantaran','poslaju','cepat','lambat','perlahan lahan','tepat pada masanya','hantar']]

In [25]:
#initialize the Translator
translator = Translator()

In [26]:
source_lan = "id"  #en is the code for Hindi Language
translated_to= "en" #hi is the code for Hindi Language

In [27]:
# df_1 = df1.iloc[:5,:]

In [28]:
df3['translated_text'] = df3['clean'].apply(lambda row: translator.translate(row, src=source_lan, dest = translated_to).text)

/var/folders/5w/0kxl7gbj5vqb93sccvkxwrzc0000gn/T/ipykernel_7291/1380100104.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['translated_text'] = df3['clean'].apply(lambda row: translator.translate(row, src=source_lan, dest = translated_to).text)

In [29]:
df3['translated_text']

78      safe packing is only slow delivery, hopefully ...
248     Fast but less neat packaging items OK Slow shi...
741     the process by a quick seller it's just just s...
1662    finally it comes too after it can be notif if ...
2541    Shipping rather slowly functioning products ca...
2772    product quality but shipping is a bit slow ove...
2936    even though the delivery was too late because ...
Name: translated_text, dtype: object